
package eliaskarimi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ApplicationError", targetNamespace = "http://eliaskarimi/error")
public class ApplicationError
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private eliaskarimi.error.ApplicationError faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ApplicationError(String message, eliaskarimi.error.ApplicationError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ApplicationError(String message, eliaskarimi.error.ApplicationError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: eliaskarimi.error.ApplicationError
     */
    public eliaskarimi.error.ApplicationError getFaultInfo() {
        return faultInfo;
    }

}
