
package eliaskarimi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "eliaskarimi.SoapService", targetNamespace = "http://eliaskarimi/", wsdlLocation = "file:/Users/marc/Documents/workspace_eclipse/IAC_OPD1/src/main/java/CitizenByDistrict.wsdl")
public class EliaskarimiSoapService
    extends Service
{

    private final static URL ELIASKARIMISOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException ELIASKARIMISOAPSERVICE_EXCEPTION;
    private final static QName ELIASKARIMISOAPSERVICE_QNAME = new QName("http://eliaskarimi/", "eliaskarimi.SoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/marc/Documents/workspace_eclipse/IAC_OPD1/src/main/java/CitizenByDistrict.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ELIASKARIMISOAPSERVICE_WSDL_LOCATION = url;
        ELIASKARIMISOAPSERVICE_EXCEPTION = e;
    }

    public EliaskarimiSoapService() {
        super(__getWsdlLocation(), ELIASKARIMISOAPSERVICE_QNAME);
    }

    public EliaskarimiSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ELIASKARIMISOAPSERVICE_QNAME, features);
    }

    public EliaskarimiSoapService(URL wsdlLocation) {
        super(wsdlLocation, ELIASKARIMISOAPSERVICE_QNAME);
    }

    public EliaskarimiSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ELIASKARIMISOAPSERVICE_QNAME, features);
    }

    public EliaskarimiSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EliaskarimiSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WS-Port")
    public WSInterface getWSPort() {
        return super.getPort(new QName("http://eliaskarimi/", "WS-Port"), WSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WS-Port")
    public WSInterface getWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://eliaskarimi/", "WS-Port"), WSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ELIASKARIMISOAPSERVICE_EXCEPTION!= null) {
            throw ELIASKARIMISOAPSERVICE_EXCEPTION;
        }
        return ELIASKARIMISOAPSERVICE_WSDL_LOCATION;
    }

}
