
package eliaskarimi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "eliaskarimi.SoapService", targetNamespace = "http://eliaskarimi/", wsdlLocation = "file:/Users/marc/Documents/workspace_eclipse/IAC_OPD1/src/main/java/CitizenByDistrict.wsdl")
public class EliaskarimiSoapService
    extends Service
{

    private final static URL ELIASKARIMISOAPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(eliaskarimi.EliaskarimiSoapService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = eliaskarimi.EliaskarimiSoapService.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/marc/Documents/workspace_eclipse/IAC_OPD1/src/main/java/CitizenByDistrict.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/marc/Documents/workspace_eclipse/IAC_OPD1/src/main/java/CitizenByDistrict.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ELIASKARIMISOAPSERVICE_WSDL_LOCATION = url;
    }

    public EliaskarimiSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EliaskarimiSoapService() {
        super(ELIASKARIMISOAPSERVICE_WSDL_LOCATION, new QName("http://eliaskarimi/", "eliaskarimi.SoapService"));
    }

    /**
     * 
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WS-Port")
    public WSInterface getWSPort() {
        return super.getPort(new QName("http://eliaskarimi/", "WS-Port"), WSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WS-Port")
    public WSInterface getWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://eliaskarimi/", "WS-Port"), WSInterface.class, features);
    }

}
