
package eliaskarimi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import eliaskarimi.request.Request;
import eliaskarimi.response.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS-Interface", targetNamespace = "http://eliaskarimi/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    eliaskarimi.response.ObjectFactory.class,
    eliaskarimi.error.ObjectFactory.class,
    eliaskarimi.request.ObjectFactory.class
})
public interface WSInterface {


    /**
     * 
     * @param parameters
     * @return
     *     returns eliaskarimi.response.Response
     * @throws ApplicationError
     */
    @WebMethod(operationName = "PopulationCountryByYear")
    @WebResult(name = "response", targetNamespace = "http://eliaskarimi/response", partName = "response")
    public Response populationCountryByYear(
        @WebParam(name = "request", targetNamespace = "http://eliaskarimi/request", partName = "parameters")
        Request parameters)
        throws ApplicationError
    ;

}
